//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADRESS { get; set; }
        public string EMAIL { get; set; }
    
        public virtual qlsv qlsv { get; set; }
    }
}
